---
# see https://github.com/FGasper/perl-github-action-tips

name: Test Code on BSD
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '13.0'
            pkginstall: pkg install -y p5-LWP-UserAgent-Cached p5-CHI p5-autodie p5-Date-Manip p5-Data-Section p5-Sort-Key-DateTime p5-GIS-Distance p5-Marpa p5-Lingua-EN-Numbers-Ordinate p5-JSON p5-Net-OAuth p5-LWP-Protocol-https p5-CPAN-DistnameInfo
          - name: openbsd
            version: '7.1'
            pkginstall: pkg_add p5-LWP-Protocol-https

    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo hostname example.com
            sudo ${{ matrix.os.pkginstall }}
            yes | sudo cpan -i App::cpanminus
            sudo cpanm -v Geo::Coder::Free
            sudo cpanm --skip-satisfied -iqn Array::Iterator Config::Auto Data::Text File::Basename File::Copy File::Temp Date::Manip Parse::RecDescent Roman FindBin Gedcom Genealogy::Gedcom::Date Date::Parse Geo::Coder::List Geo::Coder::Free IPC::System::Simple Geo::Coder::Ovi String::Compare Genealogy::Gedcom::Date Geo::Coder::RandMcnally Geo::Coder::US::Census Geo::Coder::OSM Geo::Coder::XYZ Geo::Coder::CA Lingua::EN::ABC Lingua::String Geo::Parser::Text GIS::Distance HTML::Entities Image::Info JSON List::Util LWP::Simple::WithCache MIME::Base64 LWP::UserAgent::Cached DateTime DateTime::Duration DateTime::Format::Genealogy DateTime::Format::Natural Class::Simple::Readonly::Cached Class::Simple::Cached HTML::GoogleMaps::V3 Sort::Key::DateTime Text::Names Text::Names::GB Term::ANSIColor URI URI::Find::Schemeless Locale::AU Locale::CA Locale::US XML::Dumper XML::Twig CHI Class::Simple Lingua::Conjunction Getopt::Std Lingua::EN::NameCase Lingua::EN::NameParse Lingua::EN::Inflect Locale::Object::Country Unicode::Diacritic::Strip URI::Find::Schemeless Marpa::R2 B::Lint warnings::unused Lingua::EN::Numbers::Ordinate CPAN::DistnameInfo CHI XML::Hash
            sudo cpanm --skip-satisfied -iqn LWP::UserAgent::Cached Data::Serializer
            sudo cpanm -iqn F/FR/FRIFFIN/Geo-Coder-PlaceFinder-0.1.tar.gz
            sudo chown -R runner:runner .
            perl -c -MO=Lint ./ged2site
            perl -c -Mwarnings::unused ./ged2site
            cd dynamic-site/cgi-bin && perl -c -MO=Lint ./page.fcgi '' && perl -c -Mwarnings::unused ./page.fcgi ''
            rootdir=$(pwd)/../.. perl page.fcgi page=reports
            rootdir=$(pwd)/../.. perl page.fcgi page=surnames surname='Stock%20or%20(1,2\)=(select*from(select%20name_const(CHAR(111,108,111,108,111,115,104,101,114\),1\),name_const(CHAR( <-- HERE 111,108,111,108,111,115,104,101,114\),1\)\)a\)%20--%20and%201%3D1'
